### ISSUE TITLE
"Unable to locate Java source directory" on windows

### ISSUE THREAD

**Issue by valentin-shipilov** [coconut2015/cookcc-maven-plugin#1]
The plugin doesn't work on Windows. It fails with "Unable to locate Java source directory."

Possibly this check `if (src.endsWith ("/java"))` at line 111 in CookCCMojo.java is incorrect. 

You should use File.separator instead of "/".

[stack_trace.txt](https://github.com/coconut2015/cookcc-maven-plugin/files/1546217/stack_trace.txt)

**Comment by coconut2015** [comment]
A new release 1.0.1 is made.
